server:
  #端口
  port: 8180
  servlet:
  context-path: /
#--------------------------------------------------------------------------------------------------#
spring:
  application:
    #consul里的名字，也可以在bootstarp.yml里配置
    name: ceshi
#------------------------------------------redis---------------------------------------------------#
#Redis服务器地址
  redis:
    host: 127.0.0.1
    #Redis服务器连接端口
    port: 6379
    #Redis数据库索引（默认为0）
    database:  0
    #设置密码
    password:
    #连接超时时间（毫秒）
    timeout: 1800000
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0
#--------------------------------------------------------------------------------------------------#

